language: python

sudo: required

dist: xenial

python:
  - "3.6"
  - "3.7"

cache:
  pip: true
  directories:
    - .hypothesis
    - .eggs

install:
  - sudo apt-add-repository -y ppa:nextgis/dev
  - sudo apt update
  - sudo apt install -y libgdal-dev libnetcdf-dev

script: python setup.py test

after_success:
  if [[ $(python --version) =~ "Python 3.7" ]]; then
    pip install codacy-coverage;
    python-codacy-coverage -r test-reports/coverage.xml;
  fi
