language: python

sudo: required

dist: xenial

python:
  - "3.6"
  - "3.7"

cache:
  pip: true
  directories:
    - .hypothesis
    - .eggs
    - /var/cache/apt/archives

install:
  - sudo apt-add-repository -y ppa:nextgis/dev
  - sudo apt update
  - sudo apt install -y libgdal-dev libnetcdf-dev

script: python setup.py test
