language: python

sudo: required

dist: xenial

python:
  - "3.6"
  - "3.7"

install:
  - python -m venv --system-site-packages ~/venv/satsense
  - source ~/venv/satsense/bin/activate

script: python setup.py test
