---

name: satsense
channels:
  - ioos

dependencies:
  - descartes=1.0.2
  - fiona
  - gdal
  - jupyter
  - matplotlib
  - nb_conda
  - netcdf4
  - numba
  - numpy
  - opencv
  - rasterio
  - scikit-image
  - scikit-learn
  - scipy
  - shapely
