---

name: satsense
channels:
  - ioos

dependencies:
  - affine
  - descartes
  - fiona
  - netcdf4
  - numpy
  - opencv
  - rasterio
  - scikit-image
  - scikit-learn
  - scipy
  - shapely
  # Notebooks
  - jupyter
  - matplotlib
  - nb_conda
